Implement Last-Modifed and If-Modifed-Since support
kpcyrd/rebuilderd pull request #44
Opened 2021-03-16 21:12 UTC by jelly

These changes allow imports to more efficiently detect if any data has been changed when running periodic imports of the rebuilderd data.

2021-03-17 00:00 UTC, kpcyrd requested changes

2021-03-17 00:00 UTC, kpcyrd commented on daemon/src/models/package.rs
> +    pub fn latest(connection: &SqliteConnection) -> Result<Option<NaiveDateTime>> {
```suggestion
    pub fn most_recent_built_at(connection: &SqliteConnection) -> Result<Option<NaiveDateTime>> {
```
Avoids confusion if this returns the latest built_at or the latest package :)

2021-03-17 00:00 UTC, kpcyrd commented on daemon/src/api.rs
> +    }
```suggestion
    if let Some(latest_built_at) = models::Package::latest(connection.as_ref())? {
        let latest_built_at = DateTime::from_utc(latest_built_at, Utc);

        if let Some(duration) = modified_since_duration(&req, latest_built_at) {
            if duration.num_seconds() >= 0 {
                return not_modified();
            }
        }

        let latest_built_at = SystemTime::from(latest_built_at);
        builder.set(http::header::LastModified(latest_built_at.into()));
    }
```

Needs a `use std::time::SystemTime;` at the top though :)

The compare needs to be `>=`, otherwise I couldn't get a 304 when testing with firefox because `If-Modified-Since` is equal to the last modified time.

There's a tiny chance for a race, if <write><request><write> all happen within the same second the client won't pick up the 2nd write until a 3rd write happens.

2021-03-17 00:01 UTC, kpcyrd commented
Feel free to delete the `it_works` dummy function that clippy fails on, otherwise I'd simply do that myself after the merge :)

2021-03-18 21:26 UTC, jelly commented on daemon/src/api.rs
> +    }
Yeah, I was considering the race that's why I had `>`, I'm fine with making it `>=`

2021-03-18 22:01 UTC, merged

2021-03-18 22:01 UTC, kpcyrd commented
Thanks!